blank_issues_enabled: false

contact_links:
  - name: Lockbyte
    url: https://github.com/djoezeke/lockbyte
    about: Secure Password Manager.

  - name: Lockbyte Discussions ğŸ’–
    url: https://github.com/djoezeke/lockbyte/discussions
    about: The "Discussions" forum is where you want to start.

  - name: Lockbyte Issues | Bug Bounty ğŸ
    url: https://github.com/djoezeke/lockbyte/issues
    about: Please report issues and vulnerabilities here.

  - name: Lockbyte Releases
    url: https://github.com/djoezeke/lockbyte/releases
    about: Please latest Lockbyte release here.
